name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dschu-lab'

      - name: Install dependencies
        run: npm ci --include=dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}

      - name: use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ github.run_id }}

  lint-check:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14'
          cache: 'npm'
      - name: use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ github.run_id }}
      - run: npm run lint

  code-coverage:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14'
          cache: 'npm'
      - name: use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ github.run_id }}
      - name: Run jest and check tests coverage
        run: npm run coverage
      - uses: codecov/codecov-action@v2

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14'
          cache: 'npm'
      - name: use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ github.run_id }}
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: 
      - install-dependencies
      - lint-check
      - run-tests
    name: build-and-upload
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14'
          cache: 'npm'
      - name: use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ github.run_id }}
      - run: |
          npm run build
          npm install -g surge
          surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}